### Homework 1
จงเขียนฟังก์ชัน E(x, y, z) ที่คำนวณหาค่าของสนามไฟฟ้าเนื่องจากประจุแบบจุดขนาด $-5~nC$ ซึ่งวางอยู่ที่ตำแหน่ง $(1, -2, 1)~m$ ในระบบพิกัดฉาก 3 มิติ

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from libemag.emag_initials import *
from libemag.plots import field_plot
import sympy as smp

In [7]:
# Part I : Analytical
x, y, z = smp.symbols('x, y, z', real=True)
Q = -5e-9 #nC
r = smp.Matrix([x, y, z])
rp = smp.Matrix([1, -2, 1])
R = r - rp
R.norm()

sqrt((x - 1)**2 + (y + 2)**2 + (z - 1)**2)

In [10]:
E = Q / (4. * pi * epsilon_0) * R / R.norm()**3
E

Matrix([
[ (44.9377589613059 - 44.9377589613059*x)/((x - 1)**2 + (y + 2)**2 + (z - 1)**2)**(3/2)],
[(-44.9377589613059*y - 89.8755179226117)/((x - 1)**2 + (y + 2)**2 + (z - 1)**2)**(3/2)],
[ (44.9377589613059 - 44.9377589613059*z)/((x - 1)**2 + (y + 2)**2 + (z - 1)**2)**(3/2)]])

In [9]:
E.subs({x:0., y:0., z:0.})

Matrix([
[ 3.05762721220504],
[-6.11525442441009],
[ 3.05762721220504]])

In [16]:
# Part II : Numerical
E_f = smp.lambdify([x, y, z], E)
E_f

<function _lambdifygenerated(x, y, z)>

In [17]:
E_f(0, 0, 0)

array([[ 3.05762721],
       [-6.11525442],
       [ 3.05762721]])

In [18]:
E_f(1, 2, 3)

array([[ 0.        ],
       [-2.00967768],
       [-1.00483884]])

In [19]:
E_f(100, 100, 100)

array([[-0.00085592],
       [-0.00088186],
       [-0.00085592]])

คำนวณหาค่าสนามไฟฟ้า $\mathbf{E(x, y, z)}$ ที่ตำแหน่งต่าง ๆ ตามที่นิสิตต้องการ จำนวน 5 ตำแหน่ง (ไม่ต้องพล็อตกราฟ)

In [20]:
#1 (5, 0, 5)
E_f(5, 0, 5)

array([[-0.83218072],
       [-0.41609036],
       [-0.83218072]])

In [23]:
# ขนาดของสนามไฟฟ้า E ณ จุด (5, 0, 5)
np.linalg.norm(E_f(5, 0, 5))

1.2482710822584973

In [24]:
#2 (2, 4, 6)
E_f(2, 4, 6)

array([[-0.09205002],
       [-0.55230011],
       [-0.46025009]])

### Homework 2
จงเขียนฟังก์ชัน E(x, y, z) ที่คำนวณหาค่าของสนามไฟฟ้าเนื่องจากประจุแบบเส้น ยาว $10~m$ ที่วางอยู่ตามแนวแกน $y$ ในระบบพิกัด 3 มิติ โดยที่ประจุเส้นนี้มีความหนาแน่นประจุสม่ำเสมอ และมีค่าประจุรวม $1~\mu C$

$$\mathbf{dE}=\frac{dq}{4\pi\epsilon_0}\frac{\mathbf{r-r'}}{|\mathbf{r-r'}|^3}$$
$$\frac{\mathbf{dE}}{dt}=\frac{\frac{dq}{dt}}{4\pi\epsilon_0}\frac{\mathbf{r-r'}}{|\mathbf{r-r'}|^3}$$
$$\mathbf{E(r)}=\int\mathbf{dE}$$

Line Charge Definition
$$dq=\rho_l(r')|d\mathbf{r'}|$$

Parameterised
$$dq=\rho_l(r')\left\|\frac{d\mathbf{r'}}{dt}\right\|dt$$
$$\frac{dq}{dt}=\rho_l(r')\left\|\frac{d\mathbf{r'}}{dt}\right\|$$

In [2]:
import numpy as np
import matplotlib.pyplot as plt
from libemag.emag_initials import *
from libemag.plots import field_plot
import sympy as smp

In [5]:
x, y, z, t = smp.symbols('x, y, z, t', real=True)
r = smp.Matrix([x, y, z])
rp = smp.Matrix([0, t, 0])
R = r - rp
R

Matrix([
[     x],
[-t + y],
[     z]])

In [10]:
Q = 1e-6
L = 10
rho_l = Q / L

dqdt = rho_l * smp.diff(rp, t).norm()
dqdt

1.00000000000000e-7

In [11]:
dEdt = dqdt / (4. * pi * epsilon_0) * R / R.norm()**3
dEdt

Matrix([
[                        898.755179226117*x/(x**2 + z**2 + (t - y)**2)**(3/2)],
[(-898.755179226117*t + 898.755179226117*y)/(x**2 + z**2 + (t - y)**2)**(3/2)],
[                        898.755179226117*z/(x**2 + z**2 + (t - y)**2)**(3/2)]])

In [18]:
# Definite integration from t = -5 to t = 5
smp.integrate(dEdt, (t, -5, 5))

Matrix([
[                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              

In [25]:
dEdt[0]

898.755179226117*x/(x**2 + z**2 + (t - y)**2)**(3/2)

In [33]:
# แปลงเป็น Numpy Functions
dExdt = smp.lambdify([t, x, y, z], dEdt[0])
dEydt = smp.lambdify([t, x, y, z], dEdt[1])
dEzdt = smp.lambdify([t, x, y, z], dEdt[2])

dExdt(0, 1, 2, 3)

17.157316098228257

In [36]:
quad(dExdt, -5, 5, args=(1, 2, 3))[0]

143.7621443189147

In [42]:
def E(x, y, z):
    Ex = quad(dExdt, -5, 5, args=(x, y, z))[0]
    Ey = quad(dEydt, -5, 5, args=(x, y, z))[0]
    Ez = quad(dEzdt, -5, 5, args=(x, y, z))[0]
    return np.array([Ex, Ey, Ez])

E(0.1, 0.1, 0.1)

array([8.98395462e+03, 7.18428768e+00, 8.98395462e+03])

In [41]:
np.linalg.norm(E(0.1, 0.1, 0.1))

12705.232496925531

ทดสอบการทำงานของฟังก์ชันดังกล่าว โดยนำไปใช้ในการหาค่าของสนามไฟฟ้า ณ จุดต่าง ๆ ที่แตกต่างกันตามที่นิสิตสนใจ จำนวน 4 จุด

In [44]:
#1
E(0.1, 0, 0.1)

array([8983.95892712,    0.        , 8983.95892712])